#!/usr/bin/env node

/**
 * Verification script to ensure all static assets from public/ directory
 * are included in the WXT build output.
 */

const fs = require('fs');
const path = require('path');

const PUBLIC_DIR = path.join(__dirname, '..', 'public');
const OUTPUT_DIR = path.join(__dirname, '..', '.output', 'firefox-mv2');

/**
 * Recursively get all files in a directory
 */
function getAllFiles(dir, baseDir = dir) {
  const files = [];
  const items = fs.readdirSync(dir);
  
  for (const item of items) {
    const fullPath = path.join(dir, item);
    const stat = fs.statSync(fullPath);
    
    if (stat.isDirectory()) {
      files.push(...getAllFiles(fullPath, baseDir));
    } else {
      // Get relative path from base directory
      const relativePath = path.relative(baseDir, fullPath);
      files.push(relativePath);
    }
  }
  
  return files;
}

/**
 * Check if a file should be included in the build output
 */
function shouldIncludeFile(filename) {
  // Exclude manifest.json as it's generated by WXT
  if (filename === 'manifest.json') return false;
  
  // Exclude .web-extension-id as it's a development file
  if (filename === '.web-extension-id') return false;
  
  return true;
}

console.log('🔍 Verifying static assets migration to WXT...\n');

// Get all files from public directory
const publicFiles = getAllFiles(PUBLIC_DIR)
  .filter(shouldIncludeFile)
  .sort();

console.log(`📁 Found ${publicFiles.length} files in public/ directory`);

// Check if output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
  console.error('❌ Output directory does not exist. Run "npx wxt build --browser firefox" first.');
  process.exit(1);
}

// Get all relevant files from output directory
const outputFiles = getAllFiles(OUTPUT_DIR)
  .filter(file => {
    // Only check static assets (images, CSS, etc.)
    return file.match(/\.(png|svg|css|jpg|jpeg|gif|ico|md)$/i);
  })
  .sort();

console.log(`📦 Found ${outputFiles.length} static asset files in build output\n`);

// Check each public file exists in output
let missingFiles = [];
let foundFiles = [];

for (const publicFile of publicFiles) {
  if (outputFiles.includes(publicFile)) {
    foundFiles.push(publicFile);
    console.log(`✅ ${publicFile}`);
  } else {
    missingFiles.push(publicFile);
    console.log(`❌ ${publicFile} - MISSING`);
  }
}

console.log('\n' + '='.repeat(60));
console.log(`\n📊 Summary:`);
console.log(`   Total files in public/: ${publicFiles.length}`);
console.log(`   Files found in output: ${foundFiles.length}`);
console.log(`   Missing files: ${missingFiles.length}`);

if (missingFiles.length > 0) {
  console.log('\n❌ FAILED: Some assets are missing from the build output');
  console.log('\nMissing files:');
  missingFiles.forEach(file => console.log(`   - ${file}`));
  process.exit(1);
} else {
  console.log('\n✅ SUCCESS: All static assets are included in the build output');
  console.log('\n📋 Asset categories verified:');
  
  const categories = {
    'Icons': foundFiles.filter(f => f.startsWith('icons/')),
    'Images': foundFiles.filter(f => f.startsWith('img/')),
    'CSS': foundFiles.filter(f => f.endsWith('.css')),
    'Other': foundFiles.filter(f => !f.startsWith('icons/') && !f.startsWith('img/') && !f.endsWith('.css'))
  };
  
  for (const [category, files] of Object.entries(categories)) {
    if (files.length > 0) {
      console.log(`   ${category}: ${files.length} files`);
    }
  }
  
  process.exit(0);
}
